### PR TITLE
initial code

### PR DESCRIPTION
**Pull request by rmyers808**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1)

### CODE REVIEW

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[install-testcenter.ps1, line 27 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1#-MRZDrLO26IK_2S6AL2E:-MRZDrLO26IK_2S6AL2F:bpz500s) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stc-gui/blob/fe3d075d8021d4186ef47315866687885084774b/install-testcenter.ps1#L27)):*
> ```PowerShell
> $ProgressPreference = 'SilentlyContinue'
> 
> # Install Spirent TestCenter dependencies prior to SpirentTestCenter for a silent install
> ```

TODO:  Will download vcredist from spirent S3 http.  chrome can be from google.

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @jhiga, @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[install-testcenter.ps1, line 27 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1#-MRZDrLO26IK_2S6AL2E:-MRaByTrExcfynjqFBKP:b-ojwi49) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stc-gui/blob/fe3d075d8021d4186ef47315866687885084774b/install-testcenter.ps1#L27)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

TODO:  Will download vcredist from spirent S3 http.  chrome can be from google.
</blockquote></details>

Will do that in separate review.

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1)* status: all files reviewed, 2 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[install-testcenter.ps1, line 35 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1#-MRaU7I3CUghlTc7PxWr:-MRaU7I48s-HYSXGe7rT:baww2cm) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stc-gui/blob/c6b78639cad4f25bffe1e1dbf35cae5bef8af201/install-testcenter.ps1#L35)):*
> ```PowerShell
> 
> # Install TestCenter
> Invoke-Install -FilePath "$dir/Spirent TestCenter Application.exe" -ArgumentList "/silent /pgpassword:postgres"
> ```

Does your script assume the 32-bit STC installer?  I thought 64-bit had a different file name.

We should update the README to have them download the 64-bit version.

**Comment by radhikabhat08** [comment]
___
*[install-testcenter.ps1, line 35 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1#-MReJm7t1WdmJl0tdaeT:-MReJm7t1WdmJl0tdaeU:bvhwn4w) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stc-gui/blob/c6b78639cad4f25bffe1e1dbf35cae5bef8af201/install-testcenter.ps1#L35)):*
> ```PowerShell
> 
> # Install TestCenter
> Invoke-Install -FilePath "$dir/Spirent TestCenter Application.exe" -ArgumentList "/silent /pgpassword:postgres"
> ```

This should be "Invoke-Installer" ?  is " Invoke-Install" a correct cmdlet?

**Review by jhiga — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1)* status: all files reviewed, 3 unresolved discussions (waiting on @ltran-spirent and @rmyers808)

**Review by used-to-work — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stc-gui/1#-:-MS-jhLp0Lpu2eKnjYxl:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @rmyers808)

**Pull request merged**
